// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoyUFOMdkGTUMZm0GnX-nsimqjWdgQMVA',
    appId: '1:1000627362577:web:e4ca6b5b9a257a26b18ab0',
    messagingSenderId: '1000627362577',
    projectId: 'kolibri2024-4ca74',
    authDomain: 'kolibri2024-4ca74.firebaseapp.com',
    storageBucket: 'kolibri2024-4ca74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2zA8IRHGLyozDfMNV0Buq784hl3RcPA',
    appId: '1:1000627362577:android:0a80f31f730e04d8b18ab0',
    messagingSenderId: '1000627362577',
    projectId: 'kolibri2024-4ca74',
    storageBucket: 'kolibri2024-4ca74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqOPKWVmifG6dUP_uz_P8puV6aX_JlZ-A',
    appId: '1:1000627362577:ios:a6393ee6c1dd797bb18ab0',
    messagingSenderId: '1000627362577',
    projectId: 'kolibri2024-4ca74',
    storageBucket: 'kolibri2024-4ca74.firebasestorage.app',
    iosBundleId: 'com.example.kollibry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqOPKWVmifG6dUP_uz_P8puV6aX_JlZ-A',
    appId: '1:1000627362577:ios:a6393ee6c1dd797bb18ab0',
    messagingSenderId: '1000627362577',
    projectId: 'kolibri2024-4ca74',
    storageBucket: 'kolibri2024-4ca74.firebasestorage.app',
    iosBundleId: 'com.example.kollibry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoyUFOMdkGTUMZm0GnX-nsimqjWdgQMVA',
    appId: '1:1000627362577:web:05947b12edfa9dd2b18ab0',
    messagingSenderId: '1000627362577',
    projectId: 'kolibri2024-4ca74',
    authDomain: 'kolibri2024-4ca74.firebaseapp.com',
    storageBucket: 'kolibri2024-4ca74.firebasestorage.app',
  );
}
